version: '3.8'

services:

  nginx:
    container_name: nginx_${name}
    build:
      context: ./docker
      dockerfile: nginx.dockerfile
    ports:
      - ${webport}:80
    volumes:
      - ./${project}:/var/www/backend
    depends_on:
      - mysql
      - php

  php:
   container_name: php_${name}
   build:
    context: ./docker
    dockerfile: php.dockerfile
   ports:
    - ${phpport}:9000
   volumes:
    - ./${project}:/var/www/backend
   working_dir: /var/www/backend

  mysql:
    image: mysql:5.7
    container_name: mysql_${name}
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: sudip
        MYSQL_PASSWORD: sudip
    ports:
      - ${dbport}:3306
    volumes:
      - ./docker/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/data:/var/lib/mysql
  
  node:
    container_name: node_${name}
    build:
      context: ./docker
      dockerfile: node.dockerfile
    volumes:
      - ./${project}/:/var/www/backend
    working_dir: /var/www/backend

  artisan:
    container_name: artisan_${name}
    build:
     context: ./docker
     dockerfile: php.dockerfile
    volumes:
     - ./${project}/:/var/www/backend
    working_dir: /var/www/backend
    depends_on:
     - mysql
    entrypoint: ["php", "/var/www/backend/artisan"]
   

      

