#!/usr/bin/env bash

if [ $# -gt 0 ]; then

    if [ "$1" == "up" ]; then
        docker compose up -d

    elif [ "$1" == "off" ]; then
        docker compose down
    
    elif [ "$1" == "destroy" ]; then
        docker compose down -v --rmi all --remove-orphans

    elif [ "$1" == "clearvolume" ]; then
        docker volume rm $(docker volume ls -q)

    elif [ "$1" == "nginx" ]; then
        docker compose exec nginx sh
    
    elif [ "$1" == "php" ]; then
        docker compose exec php sh

    elif [ "$1" == "mysql" ]; then
        docker compose exec mysql bash

    elif [ "$1" == "import" ]; then
        docker exec -i mysql_den mysql -h127.0.0.1 -uroot -proot dental < /Users/sudipsubedi/downloads/moo_2021.sql

    elif [ "$1" == "artisan" ] || [ "$1" == "art" ]; then
        shift 1
        docker compose exec \
            php \
            php artisan "$@"

    elif [ "$1" == "composer" ] || [ "$1" == "comp" ]; then
        shift 1
        docker compose exec \
            php \
            composer "$@"

    elif [ "$1" == "test" ]; then
        shift 1
        docker-compose exec \
            php \
            ./vendor/bin/phpunit "$@"

    elif [ "$1" == "npm" ]; then
        shift 1
        docker compose run --rm \
            node \
            npm "$@"

    elif [ "$1" == "yarn" ]; then
        shift 1
        docker compose run --rm \
            node \
            yarn "$@"

    elif [ "$1" == "gulp" ]; then
        shift 1
        docker-compose run --rm \
            node \
            ./node_modules/.bin/gulp "$@"
    else
        docker-compose "$@"
    fi

else
    docker-compose ps -a
fi